CREATE TABLE users
(
    id BIGSERIAL NOT NULL PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    socket_id VARCHAR(50),
    email VARCHAR(150) NOT NULL,
    password VARCHAR(200) NOT NULL,
    last_login DATE NOT NULL DEFAULT NOW()
);

CREATE TABLE chat
(
    id BIGSERIAL NOT NULL PRIMARY KEY,
    sender_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    receiver_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at DATE NOT NULL DEFAULT NOW(),
    updated_at DATE NOT NULL DEFAULT NOW()
);
CREATE TABLE message
(
    id BIGSERIAL NOT NULL PRIMARY KEY,
    sender_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    chat_id BIGINT NOT NULL REFERENCES chat(id) ON DELETE CASCADE,
    body TEXT NOT NULL,
    created_at DATE NOT NULL DEFAULT NOW()
);
